#!/bin/bash

DATE=$(date '+%Y-%m-%d %H:%M:%S')
BRANCH=$(git rev-parse --abbrev-ref HEAD)

echo "$USER committed to $BRANCH at $DATE" >> scratch.txt
git add scratch.txt && git commit -m "Append to scratch.txt - $DATE"
